name = "Chess"
version = "0.1.0"
defaultTargets = ["chess", "benchmark"]

[[lean_lib]]
name = "Chess"

[[lean_exe]]
name = "chess"
root = "Main"
buildType = "relWithDebInfo"

[[lean_exe]]
name = "benchmark"
root = "Chess.Benchmark"
buildType = "release"

[[require]]
name = "batteries"
scope = "leanprover-community"
rev = "main"