name = "Chess"
version = "0.1.0"
defaultTargets = ["chess"]

[[lean_lib]]
name = "Chess"

[[lean_exe]]
name = "chess"
root = "Main"

[[require]]
name = "batteries"
scope = "leanprover-community"
rev = "main"